include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Правила для работы с асинхронным кодом
    - avoid_void_async
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - throw_in_finally
    - use_rethrow_when_possible

    # Правила для работы с типами
    - always_declare_return_types
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - unrelated_type_equality_checks
    - prefer_void_to_null
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void

    # Правила для работы с виджетами и Flutter
    - avoid_web_libraries_in_flutter
    - avoid_positional_boolean_parameters

    # Правила для обработки ошибок
    - avoid_catches_without_on_clauses
    - avoid_catching_errors

    # Правила для оптимизации кода
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_unused_constructor_parameters
    - avoid_returning_this
    - empty_statements
    - hash_and_equals
    - invariant_booleans
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - unnecessary_statements
    - valid_regexps

analyzer:
  errors:
    # Отключаем предупреждения о неиспользуемых импортах
    unused_import: warning
    # Отключаем предупреждения о неиспользуемых переменных
    unused_local_variable: warning
