name: hr_tcc
description: "HR TCC project."
publish_to: 'none'
version: 0.1.2+1

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.9
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.0.0
  gap: ^3.0.1
  logger: ^2.5.0
  url_launcher: ^6.3.1
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  file_picker: ^10.2.0
  go_router: ^16.0.0
  internet_connection_checker: ^3.0.1
  flutter_sticky_header: ^0.8.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_gen_runner: ^5.10.0

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  fonts:
  - family: Roboto
    fonts:
    - asset: assets/fonts/Roboto-Regular.ttf
    - asset: assets/fonts/Roboto-Medium.ttf
      weight: 500
    - asset: assets/fonts/Roboto-Bold.ttf
      weight: 700

  assets:
  - assets/icons/tab_bar/
  - assets/icons/navigation_bar/
  - assets/icons/user_profile/
  - assets/icons/user_kpi/
  - assets/icons/auth/
  - assets/icons/keyboard/
  - assets/icons/text_field/
  - assets/icons/quick_links/
  - assets/icons/quick_links_widget/
  - assets/icons/requests/
  - assets/icons/resale/
  - assets/icons/resale_page/
  - assets/icons/news/
  - assets/icons/common/
  - assets/icons/more_page/
  - assets/icons/benefits_widget/
  - assets/icons/benefit_content/
  - assets/icons/demo/
  - assets/icons/text_field/
  - assets/icons/poll_detail_page/
  - assets/polls/
  - assets/icons/chat/
